### ISSUE TITLE
x509.certificate_managed fails when using MK20-lab-basic

### ISSUE THREAD

**Issue by samos123** [salt-formulas/salt-formula-salt#11]
I am trying out MK20 based on http://www.yet.org/2016/10/os-salt/ at the step `salt-call state.sls salt.minion` it fails. The model that I'm using is https://github.com/Mirantis/mk-lab-salt-model and I'm trying mk20-lab-basic.yaml
It looks the following code is at fault: https://github.com/tcpcloud/salt-formula-salt/blob/master/salt/minion/cert.sls#L45

The issue looks like salt.minion.cert should not be executed at all as there is no `pillar.salt.minion.cert` defined inside our model, but when debugging pillar there is some data indeed:

```
salt '*' pillar.get salt:minion:cert
cfg01.mk20-lab-basic.local:
    ----------
    proxy_cert:
        ----------
        authority:
            mk20_lab_ca
        common_name:
            _
        host:
            cfg01.mk20-lab-basic.local
        signing_policy:
            cert_server
```

Because there is data in salt.minion.cert the cert.sls gets called:
https://github.com/tcpcloud/salt-formula-salt/blob/master/salt/minion/init.sls#L10

```
salt-call state.sls salt.minion

----------
          ID: /etc/ssl/certs/_.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/x509.py", line 432, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 1098, in create_certificate
                  arg=str(kwargs))[ca_server]
              KeyError: 'cfg01.mk20-lab-basic.local'
     Started: 00:10:43.670355
    Duration: 14.039 ms
     Changes:   
----------
          ID: /etc/ssl/certs/_.crt_cert_permissions
    Function: file.managed
        Name: /etc/ssl/certs/_.crt
      Result: False
     Comment: One or more requisite failed: salt.minion.cert./etc/ssl/certs/_.crt
     Started: 
    Duration: 
     Changes:   
----------
          ID: /etc/ssl/certs/ca-mk20_lab_ca.crt_1
    Function: x509.pem_managed
        Name: /etc/ssl/certs/ca-mk20_lab_ca.crt
      Result: False
     Comment: One or more requisite failed: salt.minion.cert./etc/ssl/certs/_.crt
     Started: 
```

As a workaround I've commeted out the salt.minion.cert state in init.sls.

**Comment by seb-braun** [comment]
Same issue with the mk20-lab-basic **branch dash**

**Comment by epcim** [comment]
you have key_error. Wrong mode.

**Comment by epcim** [comment]
Happens on salt minion, something wrong is on salt-master. Copied reclass 1:1 from mk-lab-model.

``` 
...
...
Name: /etc/ssl/private/jpe2.xxx.com.key - Function: file.managed - Result: Clean Started: - 03:36:44.928573 Duration: 0.9
----------                                                                                                                      
          ID: /etc/ssl/certs/jpe2.xxx.com.crt                                                                              
    Function: x509.certificate_managed                                                                                          
      Result: False                                                                                                             
     Comment: An exception occurred in this state: Traceback (most recent call last):                                           
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call                                       
                  **cdata['kwargs'])                                                                                            
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1653, in wrapper                                   
                  return f(*args, **kwargs)                                                                                     
                File "/usr/lib/python2.7/dist-packages/salt/states/x509.py", line 432, in certificate_managed                   
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)                                             
                File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 1107, in create_certificate                  
                  arg=str(kwargs))[ca_server]                                                                                   
              TypeError: 'NoneType' object has no attribute '__getitem__'                                                       
     Started: 03:36:44.935615                                                                                                   
    Duration: 42.962 ms                                                                                                         
     Changes:                                                                                                                   
----------                                                                                                                      
          ID: /etc/ssl/certs/jpe2.xxx.com.crt_cert_permissions                                                             
    Function: file.managed                                                                                                      
        Name: /etc/ssl/certs/jpe2.xxx.com.crt                                                                              
      Result: False                                                                                                             
     Comment: One or more requisite failed: salt.minion.cert./etc/ssl/certs/jpe2.xxx.com.crt                               
     Changes:                                                                                                                   
```
